version: "3"
services:
  election-db:
    image: mysql:8
    ports:
      - "3306:3306"
    networks:
      - election-mysql-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=election_ms

  election-container:
    image: election-service
    build: ./election-service
    ports:
      - "8082:8082"
    hostname: election
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - election-mysql-network
    depends_on:
      - election-db



networks:
  election-mysql-network:
    driver: bridge