version: "2.2"

services:
  user-service:
    container_name: user-service
    build: ./
    ports:
      - "8081:8081"
    hostname: user
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://localhost:8761/eureka/
    image: "user-service"
