version: "2.2"

services:
#  Candidate:
#    container_name: eureka-server
#    build: ./
#    ports:
#      - "8761:8761"
#    hostname: eureka
#    image: "eureka-server"


    user-service:
      container_name: user-service
      build: ./user-service
      ports:
        - "8081:8081"
      hostname: user
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      image: "user-service"
      depends_on:
        - Eureka

    Eureka:
      container_name: eureka-server
      build: ./eureka-server
      ports:
        - "8761:8761"
      hostname: eureka-server
      image: "eureka-server"
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/